### ISSUE TITLE
criptography.fernet

### ISSUE THREAD

**Issue by GATOPRET0W33** [nFire-coding/passwordManager#14]
Qualcuno sa come risolvere quest'errore?
![image](https://github.com/nFire-coding/passwordManager/assets/89464321/d470c736-7b35-4305-be44-5bd562929186)

**Comment by nFire-coding** [comment]
Apri un terminale e scrivi "pip install crypthography"

**Comment by LightYagami28** [comment]
@GATOPRET0W33 se hai risolto chiudi la issues gentilmente
