### ISSUE TITLE
Cant find secret.key in the folder.

### ISSUE THREAD

**Issue by SamuZX** [nFire-coding/passwordManager#4]
Hi! So, i downloaded your password manager, installed the latest python version, set the path, installed visaul studio code and downloaded cryptography. I put "Cifra.py" into my portable ssd, but when i answer "NO" to the question it doesn't generate the file "secret.key". How can i find it? It just don't create the file (also, i have see hidden files on).
Thank you for your time!

**Comment by siissioe123** [comment]
Here's a few things you can do: 
Check File Creation Permissions: Ensure that the script has the necessary permissions to create files in the directory where it's located. Sometimes, the script might not have permission to write to certain directories.

Check Current Directory: Confirm that the script is indeed executing in the directory where you expect it to be. The secret.key file is generated in the current working directory.

Check Environment Variables: Ensure that there are no environmental variables conflicting with the script's behavior, especially those related to file paths or Python configurations.

Let me know if it works now

**Comment by siissioe123** [comment]
Did it work?

**Comment by LightYagami28** [comment]
Close this issues @SamuZX if you are resolved
